### ISSUE TITLE
Components: What components are we using from Component Library?

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/catalyst#10]
Something about Forms, InlineAlerts...

**Comment by mikemurray** [comment]
- Button
- Checkbox
- TextInput
- Select
- Form (from reacto-form)
- Field

It would seem we're mostly using the form components.

**Comment by mikemurray** [comment]
Manu of the components I've listed have been implemented. The others will be created or moved from the component-library when they're ready.
