### ISSUE TITLE
Docs: Improve overall documentation information architecture and documentation

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/catalyst#12]
After the first few components are done, we'd like to improve a few doc things:

1. Add high-level docs on what Catalyst is: it is a lightweight component library with a mix of fully-custom components and styled Material-UI components.
1. Separate the docs into Docs for Designers, Docs for Component Users (devs), and Docs for Component Modifiers (devs who will be changing how components look and work). Get Justin to help us with this.

**Comment by rymorgan** [comment]
This will be partially completed by
https://github.com/reactioncomerce/catalyst/issues/64
https://github.com/reactioncommerce/reaction/issues/5443
