### ISSUE TITLE
DataTable: label "Page" is hardcoded

### ISSUE THREAD

**Issue by janus-reith** [reactioncommerce/catalyst#123]
Type: **minor**

**Describe the bug**
The text "Page" in front of the page count is hardcoded:
https://github.com/reactioncommerce/catalyst/blob/721fc0c761ad57d3bd59caca6ddbb7b68b411f4d/package/src/components/DataTable/DataTable.js#L324

**Expected behavior**
A label for page can be passed.

**Comment by mikemurray** [comment]
That can be updated `{labels.page}`. The labels prop already has the value, but it seems I forgot to add it.
