### ISSUE TITLE
Button: Finish docs for Button

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/catalyst#16]

**Comment by machikoyasuda** [comment]
The dev side of https://catalyst.reactioncommerce.com/#/Base%20Components/Actions/Button is done. We are now importing a Material UI component into Catalyst. What kind of docs would you want to add/read for this? @rymorgan @cassytaylor

**Comment by machikoyasuda** [comment]
@mikemurray @cshepherd @kieckhafer What is `mini`? I don't see it in the MUI docs and I don't see it used anywhere in Reaction, and I don't see it used in the code. https://github.com/reactioncommerce/catalyst/blob/master/package/src/components/Button/Button.js#L90

**Comment by kieckhafer** [comment]
@machikoyasuda mini was a prop on the MUI Button in v3, which is what we were using when I wrote our Button component.

https://v3.material-ui.com/api/button/

It can be removed now that we are on MUI v4.
