### ISSUE TITLE
Component: Migrate ConfirmButton (and rename ConfirmDialog)

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/catalyst#17]
# Component Name: ConfirmDialog

### Summary description of UI component
Move component from here:
https://github.com/reactioncommerce/reaction/tree/master/imports/client/ui/components/ConfirmButton

**Comment by rymorgan** [comment]
Here are the updates designs - 
app link - zpl://screen?sid=5d37452001c2662db42f7b04&pid=5bda33eeed47f75de8f57ffb
web link - https://zpl.io/V4zv9N8
