### ISSUE TITLE
Tests: Remove enzyme; Use React Testing Library instead. Get theme in there too.

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/catalyst#19]
- remove enzyme
- use react testing lib
- add muithemeprovider to rest testing lib render method
- update all tests: ConfirmDialog, DialogTitle, Button, Chip.

**Comment by machikoyasuda** [comment]
Maybe https://testing-library.com/docs/dom-testing-library/intro ?

**Comment by nnnnat** [comment]
@machikoyasuda & @mikemurray I would really encourage this pod to explore doing component/unit test with the [React Testing Library](https://testing-library.com/docs/react-testing-library/intro) which uses the dom-testing lib @machikoyasuda linked to under the hood. I can help with setup and write a few test to show how it works but it's pretty simple to get rolling with it. I really like the philosophy behind this testing lib as it really only cares about the markup a component renders and not so much the inner working of a React component.  

I've also been in talks with @jeffcorpuz for some time about including automated user acceptance testing to our components and he's done some exploratory work using [gauge](https://gauge.org/) & [taiko](https://taiko.gauge.org/) that I think can be ported over to catalyst. I can also  help with setting that up and writing a few test to show how it works.
