### ISSUE TITLE
Theming: Move theme file into Catalyst

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/catalyst#21]
It lives `core/router/client/theme/muiTheme.js` and some of it will have to be moved,

**Comment by mikemurray** [comment]
The theme is already moved to catalyst as of this PR: https://github.com/reactioncommerce/catalyst/pull/22

**Comment by machikoyasuda** [comment]
Is it possible we separate this part of the ConfirmDialog PR into its own, so we can merge it? The ConfirmDialog PR is blocked rn and waiting on design.

**Comment by mikemurray** [comment]
It's possible, it would take a little time.
