### ISSUE TITLE
Migrate: DetailDrawer, DetailDrawerButton

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/catalyst#24]
These all seem to be interrelated. Should we migrate them at all? Opinions?

## DetailDrawerButton

<img width="1440" alt="Screen Shot 2019-07-22 at 5 26 31 PM" src="https://user-images.githubusercontent.com/3673236/61674609-6bd3bd80-aca9-11e9-8984-057201674a7e.png">

A button that opens a drawer

## DetailDrawer

The Sidebar and the right-side-bars (like Accounts) component uses the Material UI Drawer Component. The Drawer is a type of modal that is anchored to the right, left, top, or bottom of the viewport. Being a modal, it means you shouldn't depend, nor force the drawer itself to move the content out of the way. Instead, the content components should move themselves out of that way of the drawers when they're open. (See more in the Layouts section below)

**Comment by mikemurray** [comment]
`DetailDrawer` and `DetailDrawerButton` seem like decent candidates, but keep in mind these components don't work as-is. They require UIContext, that is managed by the `Dashboard` component in `Reaction`. The same is true for `Sidebar`.

The `Sidebar` component is a one-off component and has a very specific for the main navigation only. If it's going to be added to Catalyst, maybe remove the list items and `ShopLogoWithData` and make just a generic component with the dark style. Also, it's should be called `Sidebar` anymore. Perpahs `PrimaryDrawer` or something with `Drawer` as the suffix.

**Comment by machikoyasuda** [comment]
Closing this for now, as they are not priority components (yet)
