### ISSUE TITLE
Migrate: DangerChip

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/catalyst#25]
- Introduced: https://github.com/reactioncommerce/reaction/pull/5200
- Used in this monster @kieckhafer WIP PR, https://github.com/reactioncommerce/reaction/pull/5158
- What is a chip!??!?! 

https://material-ui.com/components/chips

Chips: 

<img width="985" alt="Screen Shot 2019-07-22 at 5 50 43 PM" src="https://user-images.githubusercontent.com/3673236/61674575-3f1fa600-aca9-11e9-938b-64209461f1e0.png">

**Comment by kieckhafer** [comment]
This should be updated to work like the `Button`, which used to have a separate `DangerButton` component, but is now wrapped inside our own `Button` components: https://github.com/reactioncommerce/catalyst/issues/26#issuecomment-514015330

I haven't gotten around to it yet, but was planning on updating it in https://github.com/reactioncommerce/reaction/pull/5158

**Comment by mikemurray** [comment]
Like @kieckhafer mentioned, it's going to work very much like the button component. It will pass all props down to the MUI `Chip` component. A conditional will check the `color` prop for `danger`, and adjust the color of the underlying MUI Chip component to a red color. The CSS from another color (primary, or secondary) should be copied from the MUI Chip component and replicated in the Catalyst `Chip` component exactly with the changed colors.


To break it down...

1. Call it `Chip`
2. Use the MUI `Chip` component internally
3. Override the `color` prop, look for a `danger` value
4. If `color=danger`, return a new chip with all other props except `color` destructured onto it.
5. Adjust the styles of the chip in the same way, the `primary` color is implemented here: https://github.com/mui-org/material-ui/blob/master/packages/material-ui/src/Chip/Chip.js#L49 and here: https://github.com/mui-org/material-ui/blob/master/packages/material-ui/src/Chip/Chip.js#L71
6. Ensure the prop-type definition is `color: PropTypes.oneOf(["default", "primary", "secondary", "danger"]),
7. Forward the refs: https://github.com/mui-org/material-ui/blob/master/packages/material-ui/src/Chip/Chip.js#L244

The effect we're going for here is, this component should work and feel exactly like the MUI `Chip`, just have an additional color option.
