### ISSUE TITLE
Migrate: DangerButton

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/catalyst#26]
- Introduced: https://github.com/reactioncommerce/reaction/pull/5200
- Used in this monster @kieckhafer WIP PR, https://github.com/reactioncommerce/reaction/pull/5158
- Should this be part of button? Or it's own separate thing?
- Mike's explainer on DangerButton:

```
- There is no `Danger` / `red` colored button in MUI. We built a new `Button` component, compositing the `MUI Button` that uses the same `color` prop that the MUI button expects. When the color is not `danger` the default MUI button is used. When it is `danger` the extra CSS to make it red is applied. We gain the benefit of a well-built component and add our flavor on top of it to make it better.
```

https://www.notion.so/reactioncommerce/Catalyst-UI-Overview-f39fedf1140c466ba889461e90807cc3?d=29880fc0-6950-4caf-a143-26eb7b5b2dd9#b582e87267424c9f83507517cf271554

**Comment by kieckhafer** [comment]
DangerButton no longer exists, it's gone from the `develop` branch. It existed for about a week inside that monster PR, but I ended up moving the logic into our own `Button` component, which just wraps the MUI button, and adds a red coloring for the `danger` variant.

https://github.com/reactioncommerce/reaction/blob/develop/imports/client/ui/components/Button/Button.js

**Comment by mikemurray** [comment]
The "danger" button is now part of the Button component in the catalyst. `color=danger` is the prop.

**Comment by machikoyasuda** [comment]
So it's already in the code - Now we just have to document it right?
