### ISSUE TITLE
Set up CircleCI

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/catalyst#3]
- Need catalyst module builds to be pushed to NPM

**Comment by spencern** [comment]
What needs to get setup here? Mike want to pair on this?

**Comment by machikoyasuda** [comment]
@spencern @mikemurray NPM needs to get set up to deploy `catalyst` module too.

**Comment by spencern** [comment]
Do we want to do this via `semantic-release`?

**Comment by machikoyasuda** [comment]
@spencern Of course!!!!!

**Comment by mikemurray** [comment]
@spencern So I got CircleCI working, not sure if everything else will be automatic or if we have to do the additional setup for the `semantic-release`

**Comment by machikoyasuda** [comment]
semantic-release ci instructions: https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#ci-configuration
