### ISSUE TITLE
Sidebar changes: Remove word Base; try to remove DialogTitle

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/catalyst#35]
-> Change Base Components to Components for now.
-> Remove DialogTitle from sidebar and only include it as a part of the ConfirmDialog page.

**Comment by mikemurray** [comment]
The `DialogTitle` may not be exclusive to the ConfirmDialog component, so I don't know if that warrants removing it from the navigation. Also, If the file isn't in the navigation, then the markdown file may become useless. I don't think styleguidist would render even if you knew the link (something to test). We'll run into the issue of some components have docs, and some don't when looking through the source files.

I kinda wish we could have an API section that has all the components, and the Demo section, which we have now showcasing how to use the components. And that we could collapse the menu.

**Comment by machikoyasuda** [comment]
@mikemurray We can have a Full API section and a Component/Demo section. Just gonna experiment with it and see how it looks first.

**Comment by machikoyasuda** [comment]
Confirmed!! If you don't have a component in the sidebar, you can't create a page at all. I tried removing DialogTitle from the sidebar, but when I did, http://localhost:4060/#/Base%20Components/Feedback/DialogTitle goes to Page Not Found. @mikemurray you were right!
