### ISSUE TITLE
Forms: Migrate `TextInput` component to Catalyst

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/catalyst#42]
# Component Name
TextInput

## Overview / Summary
`TextInput` is a component which provides various `input` fields for forms. See our previous version: https://designsystem.reactioncommerce.com/#/Base%20Components/Forms/TextInput

Our design system version is missing essential props, including `min` and `max`, as well as the ability to be a `number` input. The `Catalyst` version should provide these features.

### Summary description of UI component
An `input` field for text

### Rationale for why this component is necessary
The `TextInput` component in the design system needs some updates. Instead of completely overhauling it there, it would be great to get it incorporated here and use the new version

### Expected use cases
Anywhere an `input` field is used in a form

**Comment by mikemurray** [comment]
closed by #143
