### ISSUE TITLE
Typography: Add `-webkit-font-smoothing: antialiased;` to all fonts at all sizes

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/catalyst#49]
Figure out how to add this style to MUI's Typography component

**Comment by nnnnat** [comment]
I'm not sure we need to do this, I'm under the impression that it's best practice not to use the `font-smoothing` CSS properties because of poor support. [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth)

**Comment by machikoyasuda** [comment]
Ah... true.

We've added font-weight: 600 semibold of Source Sans Pro, and this is what the buttons look with and without antialiasing, compared with Zeplin:

***-webkit-font-smoothing: auto vs. Zeplin***: button text looks really big compared to comp
<img width="555" alt="Screen Shot 2019-08-06 at 3 02 55 PM" src="https://user-images.githubusercontent.com/3673236/62580716-b9c8f380-b85b-11e9-8086-670910cc2c62.png">

***-webkit-font-smoothing: antialiased vs. Zeplin*** button text matches comp
<img width="413" alt="Screen Shot 2019-08-06 at 3 04 24 PM" src="https://user-images.githubusercontent.com/3673236/62580717-b9c8f380-b85b-11e9-9192-c56c54ade347.png">

And I just checked to see what Google Web Fonts does for their site, and alas, they use antialiasing on their whole site, including the page for Source Sans Pro: https://fonts.google.com/specimen/Source+Sans+Pro

We'll have to figure out if we just have to deal with this discrepancy between the app and Zeplin/comps or there's anything else we can do. For me personally I'd want the comps and app to look as close as possible. Not sure if there's a way to get Zeplin to show the font w/o the antialiasing... but that would make it easier for me to visually QA stuff.

**Comment by nnnnat** [comment]
I sure if there is much more we can do to get them to render the same between the mock and whats in the browsers. There are just too many variables to how text gets rendered (screen resolution, graphic card, browser) to make it match perfect. I think the best we can do is verify all the correct families and weights are being defined/provided and rendering in each supported browser.

**Comment by mikemurray** [comment]
We should let the fonts render the way the browser intends with the default font smoothing. HiDPI displays make anti-aliasing unnecessary.
