### ISSUE TITLE
Update Catalyst docs navigation to reflect this structure + And write/edit/publish the docs

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/catalyst#64]
Not all of these pages are v1 but wanted to play out how this structure would work going forward. The content for the proposed pages isn't polished but we can start to use this navigation to pull it together from various notion documents that are floating around. 

https://docs.google.com/spreadsheets/d/1qu4q8x4Rl2ftlXr_lRwRNlUsWUapfRXERD1BsH4PUBw/edit#gid=0

**Comment by machikoyasuda** [comment]
<img width="1005" alt="Screen Shot 2019-08-16 at 2 22 47 PM" src="https://user-images.githubusercontent.com/3673236/63199011-5c8a2a80-c031-11e9-9d4f-42223af6cc54.png">
Comparing the doc w/ where we are at now.

I think there will be a need for more dev-focused docs/how to guides in the future. Should all of those go under "Overview", or should we make a separate "Developers" section? Some of these guides are fairly technical and don't apply to everyone: https://catalyst.reactioncommerce.com/#/Introduction/Understanding%20Component%20References https://catalyst.reactioncommerce.com/#/Developers/Developing%20Locally%20Inside%20Another%20Project

**Comment by rymorgan** [comment]
@machikoyasuda Yes, maybe we add a developers section? I'd like to make these docs a little more usable than they are now. Unless they make sense to devs?

**Comment by machikoyasuda** [comment]
Yeah I think we can put a Dev section in between Foundations & Components.

**Comment by rymorgan** [comment]
@machikoyasuda Can you fill in what items would potentially be in the dev section?

**Comment by machikoyasuda** [comment]
@rymorgan Done. I also added a column on the status of the docs, whether it's written yet or not.
