### ISSUE TITLE
Document x Code: Establish set colors for Order Statuses

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/catalyst#65]
## Goal

Reaction developers, designers and plugin developers should have a guide on how to represent order statuses on Reaction apps. We can document and enforce that here with Catalyst code and docs.

We should decide and document:
- Come up with a color for each Order Status
- Document what color should be used with each Order Status
- Also document other details like, how should an Order Status be capitalized? `Order cancelled` v. `Order Cancelled` (vs. `Order Canceled` or `Order Cancelled`).
- And then implement the code to make this happen

## Deliverables

Two pull requests:
1. One PR for the design requirements
1. One PR for the code to make #1 happen.

**Comment by rymorgan** [comment]
@machikoyasuda cc @kieckhafer Do we have a list of all the current order statuses?

**Comment by machikoyasuda** [comment]
yes. https://github.com/reactioncommerce/reaction/pull/5158

```"orderStatusLabels": {
    "new" : [ 
        {
            "language" : "en",
            "label" : "Order received"
        }, 
        {
            "language" : "es",
            "label" : "Recibido"
        }
    ],
    "coreOrderWorkflow/processing" : [ 
        {
            "language" : "en",
            "label" : "Order received"
        }, 
        {
            "language" : "es",
            "label" : "Recibido"
        }
    ],
    "coreOrderWorkflow/completed" : [ 
        {
            "language" : "en",
            "label" : "Shipped"
        }, 
        {
            "language" : "es",
            "label" : "Enviado"
        }
    ],
    "coreOrderWorkflow/canceled" : [ 
        {
            "language" : "en",
            "label" : "Canceled"
        }, 
        {
            "language" : "es",
            "label" : "Cancelado"
        }
    ],
    "coreOrderWorkflow/picked" : [ 
        {
            "language" : "en",
            "label" : "Picked"
        }
    ],
    "coreOrderWorkflow/packed" : [ 
        {
            "language" : "en",
            "label" : "packed"
        }
    ],
    "coreOrderWorkflow/shipped" : [ 
        {
            "language" : "en",
            "label" : "shipped"
        }
    ]
}
```

**Comment by rymorgan** [comment]
Perfect, we can assign colors to these.

**Comment by machikoyasuda** [comment]
And then we can document them using Chips! :D

**Comment by machikoyasuda** [comment]
There are 4 overall orders statuses: New, Processing, Completed, Canceled (this is unchanged)

- New: A new order; no fulfillment/payment actions have been taken yet
- Processing: Payment and/or fulfillment are in progress (payment captured, order partially shipped, etc.)
- Completed: An order that has been paid and fulfilled (shipped)
- Canceled: an order has been canceled (possible only up until the fulfilled/shipped stage?)

Fulfillment statuses:
- We are proposing simplifying fulfillment statuses to Unfulfilled, Partially fulfilled, and Fulfilled. (This would replace our current steps, picked, packed, labeled, shipped etc - although a shop should hypothetically be able to configure their own statuses.)

- A partially fulfilled order would indicate an order with multiple fulfillment group, with a mix of unfulfilled/fulfilled groups (is there any other time this status would show up?)

Payment statuses: 

These should come from Stripe or other payment providers. Currently we are thinking Authorized, Paid, Refunded, and Unpaid. 

Should there be any others (or other considerations for payment statuses)?

Overall orders status, fulfillment status, and payment status appear both in the Orders table and the Order detail view. The overall order status applies to the order as a whole, but an order can have different fulfillment/payment statuses if there are multiple fulfillment groups or payments used. 

We currently convey this with a “Multiple statuses” badge alongside the overall order status badge.

Proposed rule: An order should only have the “Completed” status when all fulfillment groups have been shipped (fulfilled) and all payments have been paid. (edited)

**Comment by machikoyasuda** [comment]
- Start with defining the possible statuses for each payment and for each fulfillment group.
- Decide will there be a order payment status calculated from applying logic to the individual payment statuses?
- Decide will there be a order fulfillment status calculated from applying logic to the individual fulfillment group statuses?
- A generic order status would be derived from combining the above statuses. Is this needed? If the only use case is to filter on completed, could we have an “isCompleted” true/false instead? Maybe even have the user mark it completed in the UI rather than some complex state machine logic to try to guess whether it’s completed? (Simplicity is best here.)
- Each type of order status (payment, fulfillment, general) should be associated with an auth permission, and a user with that permission should be able to directly set the status, circumventing our default status determination logic.
- Following the above point, our design should consider what it means for every status to change in every possible direction. For example, why would a payment status change from “Paid” to “Refunded”, and what should that trigger (if anything). Same thought exercise for every possible status pair.
- This isn’t necessarily a UI thing, but I lean away from any breaking changes to order statuses since they’re used so much in integrations with external systems. My thought was that we put the statuses and status logic into the database, and provide a UI allowing you to change what you call each status. (Erik already has this partially done, with ability to provide translations of each status, too.) This would mean we don’t have to do an automatic migration to different statuses in the database and potentially break some integrations, but admins would be able to manually change statuses and migrate after confirming that their integrations will handle the new status strings.
