### ISSUE TITLE
Components: Move a component from Reaction into Catalyst

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/catalyst#9]
## Context

Currently, the Storefront Admin component code lives in Reaction. We'd like to move the component code out into Catalyst.

## Process

1. Copy code from a component, for example, `PrimaryAppBar`, from `reaction` and put it into `catalyst`.
1. Document `PrimaryAppBar` in Styleguidist. Keep the docs lightweight. These docs will replace what @mikemurray  has already written here: https://docs.reactioncommerce.com/docs/components-primary-app-bar These docs should be useful for designers and devs. These docs should not include any information otherwise available on the internet, and it should not include any specs that can be derived from the code. (For example, if the padding on something is 12px, don't document it. A designer/dev can figure that about by using some tools).
1. Get @nnnnat and @jeffcorpuz to review the new component. They should tell us everything we need to do to test the accessibility of this component, whether that's through code or manual testing. Remind them to test it on MOBILE too.
1. Get @cassytaylor and @rymorgan to do a design review of the new component. They can use the component with the amazing branch deploys.
1. Once the PR is reviewed, publish the new component to NPM.
1. Use the new `catalyst` component `PrimaryAppBar` in `reaction` itself. Delete the `PrimaryAppBar` code in `reaction` (if possible).

We should also document this process, for us as devs, and publish that in Notion and/or in this repo in the `docs` repo. @mikemurray  has already started that here: https://www.notion.so/reactioncommerce/Moving-components-from-Reaction-Adding-new-components-0e236a9e2b3947ab96a956138145e194

## Which components to work on first? And in what order?

@rymorgan and I (@machikoyasuda) came up with a list and way to prioritize what components to convert first, but we'd like everyone's input too.

Phase 1: All the components required for a basic Storefront Admin page, that already lives in Reaction

<img width="776" alt="Screen Shot 2019-07-19 at 1 11 18 PM" src="https://user-images.githubusercontent.com/3673236/61562698-b7c30000-aa26-11e9-878b-6724970bf026.png">

- `Dashboard` - Main wrapper of the Operator experience
- `PrimaryAppBar` - Main toolbar at the top.
- `Sidebar` - Main navigation bar, is a single use component
- Main content areas layouts like:
    - ContentViewStandardLayout - Max width 1140px, centered content, scrolls
    - ContentViewFullLayout - Max with 100% - left/right padding, scrolls
    - ContentViewExtraWideLayout - Max width 100vw & height 100vh (viewport width and height), does not scroll

Phase 2: Alerts - and other _smaller scale_ components that will be required for the new Bulk Tag Action feature:

- Toast: <img width="387" alt="Screen Shot 2019-07-19 at 1 27 49 PM" src="https://user-images.githubusercontent.com/3673236/61563670-60725f00-aa29-11e9-88f0-4c7fff96f1ae.png">
- Notification modal question asker window: <img width="716" alt="Screen Shot 2019-07-19 at 1 27 37 PM" src="https://user-images.githubusercontent.com/3673236/61563669-60725f00-aa29-11e9-82b0-4d3b547bf87c.png">
- The ugly notification modal bouncy box: Example - the Delete a tag one <img width="1161" alt="Screen Shot 2019-07-19 at 1 28 51 PM" src="https://user-images.githubusercontent.com/3673236/61563672-60725f00-aa29-11e9-8397-6d0425fb9d02.png">

**Comment by machikoyasuda** [comment]
<img width="181" alt="Screen Shot 2019-07-22 at 12 25 32 PM" src="https://user-images.githubusercontent.com/3673236/61659218-e0900300-ac7b-11e9-81b8-eb0e93731216.png">

Stuff to move over ☝️

**Comment by machikoyasuda** [comment]
Does a Dashboard and Layouts make sense as Catalyst components? @rymorgan

**Comment by nnnnat** [comment]
@machikoyasuda @cassytaylor & @rymorgan for Phase 1 we should include a [skip-nav](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-skip.html) ([TL;DR](https://a11yproject.com/posts/skip-nav-links/)) component. Managing user focus is critical to keeping our UI accessible and this is a great place for us to start designing & testing for one of the more complicated parts of web accessibllity. We'll need to design and document the intended keyboard driven user flow for the main layout and how that might change after navigating to different pages/views within the UI. I see this a prerequist for the Alerts & Modal work of Phase 2 and the inherit focus problems that come with those types of UI elements.

**Comment by rymorgan** [comment]
@nnnnat Pardon my ignorance -- Is there a way to target screen readers? OR does a skip nav component need to be embedded on every page? 

> @machikoyasuda @cassytaylor & @rymorgan for Phase 1 we should include a [skip-nav](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-skip.html) ([TL;DR](https://a11yproject.com/posts/skip-nav-links/)) component. Managing user focus is critical to keeping our UI accessible and this is a great place for us to start designing & testing for one of the more complicated parts of web accessibllity. We'll need to design and document the intended keyboard driven user flow for the main layout and how that might change after navigating to different pages/views within the UI. I see this a prerequist for the Alerts & Modal work of Phase 2 and the inherit focus problems that come with those types of UI elements.

**Comment by rymorgan** [comment]
@machikoyasuda Yes, they do. But we should make sure we sync about what we all mean by those things? 

> Does a Dashboard and Layouts make sense as Catalyst components? @rymorgan

**Comment by nnnnat** [comment]
@rymorgan there are ways using HTML/CSS to explicitly show or hide content to a screen reader but targeting one via javascript is pretty discouraged. As for the skip-nav it would be on every page just like the main navigation, [walmart.com](https://walmart.com), [target.com](https://target.com) and [pandaexpress.com](https://www.pandaexpress.com/) have a few good examples (load the page an press `tab` key until you see the skip nav appear, it should be the first thing that happens when the user focus enters the webpage).  Most the time it will have only 1 link to change the focus to the main content section skipping the top bar and navigation that's in the view, but it might need more if we see a need.

**Comment by machikoyasuda** [comment]
Done.

**Comment by rymorgan** [comment]
@machikoyasuda Did we capture this skip nav in another issue?

**Comment by machikoyasuda** [comment]
@rymorgan no. we should add it as a requirement for all future modals/dialogs.

**Comment by rymorgan** [comment]
@machikoyasuda @nnnnat Isn't this a little more foundational than that. @nnnnat Maybe you can help us capture this in an issue. I don't know if I have enough of an understanding write an issue that is actionable that makes sense. That said, it feels very important for accessibility.
